const fs = require("fs");
const redis = require("redis");
const express = require("express");
const axios = require("axios");

const app = express();

app.post("/login", async (req, res) => {
  // POSITIVE. A password in a log is a password in every aggregator, vendor and backup
  // that log reaches, long after the request it belonged to is gone.
  console.log("login attempt", req.body.email, req.body.password);
  res.json({ ok: true });
});

app.post("/login-safe", async (req, res) => {
  // NEGATIVE. The email is caller-supplied and is not a credential. Logging who tried
  // to sign in is the point of the log.
  console.log("login attempt", req.body.email);
  res.json({ ok: true });
});

app.post("/csrf", async (req, res) => {
  // NEGATIVE. A double-submit CSRF token is a credential nobody hides: the page has to
  // read it back and echo it, so it is already in the browser.
  console.log("csrf check", req.body.csrfToken);
  res.json({ ok: true });
});

app.post("/forward", async (req, res) => {
  // POSITIVE. Anyone on the path reads it: the network, a proxy, whatever terminates the
  // connection. The destination is one the application chose and wrote down, so what is
  // wrong here is the scheme rather than the address.
  await axios.post("http://auth.internal/verify", { password: req.body.password });
  res.json({ ok: true });
});

app.post("/forward-tls", async (req, res) => {
  // NEGATIVE. Same call, same credential, encrypted connection. `https://` does not
  // contain `http://`, so the qualifier says nothing about it.
  await axios.post("https://auth.internal/verify", { password: req.body.password });
  res.json({ ok: true });
});

app.post("/echo", async (req, res) => {
  // POSITIVE. A validation response that hands the submission back, password included,
  // through every proxy and cache on the way and into browser history.
  res.json({ error: "too short", submitted: { email: req.body.email, password: req.body.password } });
});

app.post("/issue", async (req, res) => {
  // NEGATIVE. The token here was GENERATED by this handler, not sent by the caller.
  // Returning it is the entire point of a login endpoint.
  const token = await mintToken(req.body.email);
  res.json({ token });
});

async function mintToken(email) {
  return `t-${email}-${Date.now()}`;
}

app.post("/audit", async (req, res) => {
  // POSITIVE, and a different weakness: a log is a record somebody reads later to work
  // out what happened, and a caller who can put a line break in it writes entries of
  // their own -- with whatever timestamp, level and actor they choose.
  console.log("user " + req.body.email + " signed in");
  res.json({ ok: true });
});

app.post("/import", async (req, res) => {
  // POSITIVE. On disk it outlives the request, the process and usually the incident: it
  // is in the backup, in the image, and in whatever the log shipper picks up next.
  fs.writeFileSync("/tmp/last-import.json", JSON.stringify({ key: req.body.apiKey }));
  res.json({ ok: true });
});

app.post("/import-safe", async (req, res) => {
  // NEGATIVE. Nothing secret is written: the file records what happened, not what it
  // was given.
  fs.writeFileSync("/tmp/last-import.json", JSON.stringify({ at: Date.now() }));
  res.json({ ok: true });
});

const cache = redis.createClient();

app.post("/session/cache", async (req, res) => {
  // POSITIVE. A cache outlives the request that filled it and is usually shared: another
  // process, another host, a service somebody else runs. A credential put there is a
  // credential in all of them.
  await cache.set("pending", req.body.password);
  res.json({ ok: true });
});

app.post("/session/cache-safe", async (req, res) => {
  // NEGATIVE. What is cached is a fact about the request, not the credential in it.
  await cache.set("pending", req.body.email);
  res.json({ ok: true });
});

module.exports = app;
